// Single source for the home view AND the generated SKILL.md (AXI
// principle 7). Edit here; skills/porkbun-axi/SKILL.md is regenerated by
// `npm run skill:gen` and CI fails if it drifts (`npm run skill:check`).

import { homedir } from "node:os";
import { emitBlock, emitList } from "../output/toon.js";
import { helpBlock } from "../output/suggest.js";

export const DESCRIPTION = "Safe, agent-ergonomic domain management through the Porkbun API";

export const SPEC_VERSION = "axi/1.0-2026-07";

export function collapseHome(path: string): string {
  const home = homedir();
  return path.startsWith(home) ? "~" + path.slice(home.length) : path;
}

/**
 * Shared body of the home view; `tool` is how commands are written.
 *
 * The home view is intentionally credential-free so discovery never triggers
 * a network call and credentials are never needed merely to inspect the CLI.
 */
export function homeBody(tool: string): string {
  const table = emitList("capabilities", [
    { group: "domains", operations: "list,get,check,pricing,register", safety: "register requires --confirm after price quote" },
    { group: "dns", operations: "list,get,create,update,delete", safety: "update/delete require --confirm" },
    { group: "forwarding", operations: "list,create,delete", safety: "delete requires --confirm" },
    { group: "ssl", operations: "retrieve", safety: "read-only" },
    { group: "nameservers", operations: "get,set", safety: "set requires --confirm" },
    { group: "glue", operations: "list,create,update,delete", safety: "update/delete require --confirm" },
  ], ["group", "operations", "safety"]);
  const help = helpBlock([
    `${tool} domains list`,
    `${tool} domains pricing --tlds com,net`,
    `${tool} --help`,
  ]);
  return [table, help].join("\n");
}

export function renderHome(binPath: string): string {
  const header = `porkbun-axi: ${collapseHome(binPath)} - ${DESCRIPTION}`;
  return [header, homeBody("porkbun-axi")].join("\n");
}

/** Full tool reference for `porkbun-axi --help`. */
export function rootHelpText(): string {
  const commands = emitList(
    "commands",
    [
      { command: "domains list|get|check|pricing|register", summary: "Inspect domains, prices, availability, or register" },
      { command: "dns list|get|create|update|delete", summary: "Manage DNS records" },
      { command: "forwarding list|create|delete", summary: "Manage URL forwards" },
      { command: "ssl retrieve", summary: "Retrieve a PEM certificate bundle" },
      { command: "nameservers get|set", summary: "Inspect or replace nameservers" },
      { command: "glue list|create|update|delete", summary: "Manage registry glue records" },
    ],
    ["command", "summary"],
  );
  const flags = emitList(
    "flags",
    [
      { flag: "--help", default: "", description: "show help for any command" },
      { flag: "--version", default: "", description: "print the tool version" },
    ],
    ["flag", "default", "description"],
  );
  return [
    `porkbun-axi: ${DESCRIPTION}`,
    commands,
    flags,
    emitBlock("examples", [
      "porkbun-axi domains list",
      "porkbun-axi dns create example.com --type A --name www --content 192.0.2.1",
      "porkbun-axi nameservers set example.com --servers ns1.example.net,ns2.example.net --confirm",
    ]),
  ].join("\n");
}

/** The static SKILL.md: home content with checkout-based command forms. */
export function renderSkill(): string {
  const frontmatter = [
    "---",
    "name: porkbun-axi",
    `description: "${DESCRIPTION.replace(/"/g, "'")}"`,
    "---",
  ].join("\n");
  const body = [
    "# porkbun-axi",
    "",
    `${DESCRIPTION} (built against AXI spec ${SPEC_VERSION}). Install from a checkout of this repository (\`npm install && npm run build && npm link\`), then run the \`porkbun-axi\` commands below. Without linking, \`node bin/porkbun-axi.js\` from the checkout takes the same arguments.`,
    "",
    "```",
    homeBody("porkbun-axi"),
    "```",
    "",
    "Every command supports `--help`. Exit codes: 0 success/no-op, 1 error, 2 usage error. All output is TOON on stdout.",
  ].join("\n");
  return [frontmatter, "", body, ""].join("\n");
}
